# Generated by Django 5.2.12 on 2026-04-04 03:11

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('project_type', models.CharField(choices=[('web', 'Web Application'), ('data', 'Data Engineering'), ('scraping', 'Web Scraping'), ('analysis', 'Data Analysis'), ('api', 'API / Backend'), ('other', 'Other')], default='web', max_length=20)),
                ('short_description', models.CharField(help_text='Shown on the project card (max 180 chars)', max_length=180)),
                ('description', models.TextField(help_text='Full project description shown on detail page')),
                ('image', models.ImageField(blank=True, help_text='Project screenshot or cover image', null=True, upload_to='projects/')),
                ('github_url', models.URLField(blank=True, null=True)),
                ('live_url', models.URLField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False, help_text='Show this project on the homepage')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number = appears first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='Comma-separated tags e.g. Python, Django, Pandas', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
